libocca/occa

- include/occa/defines/CUDA.hpp
- include/occa/defines/OpenCL.hpp
- include/occa/defines/OpenMP.hpp
- include/occa/defines/Pthreads.hpp
- include/occa/defines/Serial.hpp
> [Defines] Adding hypot function to the defines

- examples/addVectors/loopy/ISPC.hpp
- examples/addVectors/loopy/addVectors.floopy
- examples/addVectors/loopy/main.cpp
- examples/addVectors/loopy/makefile
This is an example @inducer and I cooked up to call loopy kernels from
occa.  The OpenCL, CUDA, and ispc backends have been tested and seem to
work.
> Add loopy addVectors example

- include/occa/defines.hpp
- src/CUDA.cpp
Here are some fixes that address the errors seen in #19.
> Fixes for CUDA

- include/occa/modes/cuda/utils.hpp
- src/modes/cuda/utils.cpp
Required fix to compile with commit 356246.
> [CUDA] Include memory header

- include/occa/cBase.hpp
- src/cBase.cpp
@dmed256 : I am planning to add a few functions to OCCA C API that we
need when porting Nek5000/Nekbone to be run with OCCA. We prefer
using C API in Nek5000/Nekbone rather than C++.
Are you fine with merging these changes into OCCA master?
I have added a function to get a list of available devices on the node so that
each MPI rank can select one. Let me know if this is okay. I will keep adding
some other functions we will be needing in future.
> [WIP] Update C API for using in Nek5000/NekBone

- scripts/occa.cpp
These are my changes to resolve Issue #155 .
> Fixes for issue #155

- include/occa/array/linalg.tpp
Fix for small bug found using ASAN: mismatched new/delete.
> Fix mismatched new/delete

- Makefile
- scripts/Makefile
* Added soname (install_name) field
* use .dylib as extension on OS/X
> soname changes for libocca.so

- CMakeLists.txt
- bin/CMakeLists.txt
- cmake/Metal.cmake
- cmake/OS.cmake
- cmake/OpenCL.cmake
- cmake/OpenMP.cmake
- scripts/compiledDefinesTemplate.hpp.in
- src/CMakeLists.txt
> [CMake] OpenMP support is now optional.

- config.default.json
- src/core/kernel.cpp
Updates the `header` -> `headers` kernel prop and fixes bug with it
> [Kernel] Fix headers prop

- src/modes.cpp
Throw exception using OCCA_ERROR if mode does not exist or not enabled
> Issue#232: Assert chosen mode exists

- src/modes.cpp
> Revert "Issue#232: Assert chosen mode exists"

- include/occa/modes/cuda/polyfill.hpp
- include/occa/modes/hip/polyfill.hpp
- src/core/memory.cpp
- src/modes/cuda/device.cpp
- src/modes/hip/kernel.cpp
- Removes some compiler warnings
> [Make] Removes compiler warnings

- CMakeLists.txt
> [CMake] Do not pass incompatible flags to Intel compilers

- CMakeLists.txt
- src/modes/serial/device.cpp
A couple of annoyances with recent cmake version. 
This also fixes a complaint from Intel compiler.
> Cmake fixes

- src/modes/cuda/device.cpp
ptx was missing the user provided includes - this is a one line fix.
> FIX: ptx compilation in native CUDA mode was missing include files

- include/occa/c/device.h
- include/occa/c/dtype.h
- include/occa/c/kernel.h
- include/occa/c/memory.h
- include/occa/c/properties.h
- include/occa/c/types.h
- include/occa/c/uva.h
- src/c/device.cpp
- src/c/dtype.cpp
- src/c/kernel.cpp
- src/c/memory.cpp
- src/c/properties.cpp
- src/c/types.cpp
- src/c/uva.cpp
This is a follow-up of PR #318 and #331. Sorry, I missed those ones before.
> [C] Use bool instead of int for boolean types everywhere

- Makefile
- scripts/Makefile
- tests/run_bin_tests
Fix some minor issues in the makefiles and test scripts.
> [Build][CI] Minor fixes

- include/occa/lang/builtins/attributes/restrict.hpp
- include/occa/lang/transforms/builtins/restrict.hpp
- src/lang/builtins/attributes/restrict.cpp
- src/lang/parser.cpp
- src/lang/specialMacros.cpp
- src/lang/transforms/builtins/restrict.cpp
Fixes #343 and fixes a warning about an unreachable statement.
> Fix issues with PGI compiler

- .github/workflows/build.yml
> [CI] Adds codecov back

- include/occa/lang/parser.hpp
- src/lang/parser.cpp
- src/lang/statementPeeker.cpp
- tests/files/addVectors.okl
Fixes storing standard headers in `directiveStatement`s
> [Parser] Adds directiveStatement from directiveToken

- .github/workflows/build.yml
- include/occa/api/metal/buffer.hpp
- include/occa/api/metal/commandQueue.hpp
- include/occa/api/metal/device.hpp
- include/occa/api/metal/event.hpp
- include/occa/api/metal/function.hpp
- include/occa/lang/file.hpp
- include/occa/lang/primitive.hpp
- include/occa/tools/env.hpp
- include/occa/tools/properties.hpp
- scripts/Makefile
- src/api/metal/buffer.mm
- src/api/metal/commandQueue.mm
- src/api/metal/device.mm
- src/api/metal/event.mm
- src/api/metal/function.mm
- src/api/metal/polyfill.cpp
- src/lang/file.cpp
- src/lang/tokenContext.cpp
- src/modes/cuda/device.cpp
- src/modes/cuda/kernel.cpp
- src/modes/cuda/memory.cpp
- src/modes/cuda/utils.cpp
- src/modes/opencl/utils.cpp
- src/tools/env.cpp
- src/tools/properties.cpp
- src/tools/sys.cpp
- tests/files/addVectors.okl
- tests/files/argKernel.okl
- tests/run_tests
Adds warnings-as-error flag along with other useful warning flags
> [CI] Adds error flags to CI build

- include/occa/lang/parser.hpp
- src/lang/parser.cpp
- tests/files/addVectors.okl
Comments were being put into blocks too aggresively.
> [Parser] Fixes comments on blocks

- README.md
- bin/occa.cpp
Just a couple small additions to print out useful env variables for the HIP backend in the CLI.
> [HIP] Small QoL updates for HIP in Readme and CLI

- bin/occa.cpp
- include/occa/modes.hpp
- include/occa/modes/cuda/registration.hpp
- include/occa/modes/hip/registration.hpp
- include/occa/modes/metal/registration.hpp
- include/occa/modes/opencl/registration.hpp
- include/occa/modes/openmp/registration.hpp
- include/occa/modes/serial/registration.hpp
- src/core/base.cpp
- src/modes.cpp
- src/modes/cuda/registration.cpp
- src/modes/hip/registration.cpp
- src/modes/metal/registration.cpp
- src/modes/opencl/registration.cpp
- src/modes/openmp/registration.cpp
- src/modes/serial/registration.cpp
- tests/src/modes.cpp
Refactors how mode registration works and fixes #382 by lazily initializing modes
> [Core] Refactors mode registration and adds lazy initialization

- include/occa/lang/expr.hpp
- include/occa/lang/expr/expr.hpp
- include/occa/lang/expr/primitiveNode.hpp
- src/lang/builtins/attributes/dim.cpp
- src/lang/builtins/attributes/tile.cpp
- src/lang/expr/expr.cpp
Adds `occa::lang::expr` to make code transformations easy!
```cpp
exprNode *index = call.args[order[dimCount - 1]];
for (int i = (dimCount - 2); i >= 0; --i) {
const int i2 = order[i];
token_t *source = call.args[i2]->token;
exprNode *indexInParen = index->wrapInParentheses();
// Don't delete the initial call.args[...]
if (i < (dimCount - 2)) {
delete index;
}
exprNode *dimInParen = dimAttr.args[i2].expr->wrapInParentheses();
binaryOpNode mult(source,
op::mult,
*dimInParen,
*indexInParen);
delete dimInParen;
delete indexInParen;
parenthesesNode multInParen(source,
mult);
exprNode *argInParen = call.args[i2]->wrapInParentheses();
index = new binaryOpNode(source,
op::add,
*argInParen,
multInParen);
delete argInParen;
}
exprNode *newValue = new subscriptNode(call.token,
*(call.value), …
```
> [Lang][Expr] Adds expr: expression builder helper

- src/lang/modes/serial.cpp
Adds back the `@exclusive` initialization
> [Lang] Add @.exclusive initialization

- src/tools/cli.cpp
Uses `bash` defaults for file autocomplete
> [CLI] Does proper file completion

- cmake/FindHIP.cmake
> [HIP][CMake] Propagating build system change in libocca/occa#421 to cmake

- include/occa/modes.hpp
- include/occa/modes/cuda/registration.hpp
- include/occa/modes/hip/registration.hpp
- include/occa/modes/metal/registration.hpp
- include/occa/modes/opencl/registration.hpp
- include/occa/modes/openmp/registration.hpp
- include/occa/modes/serial/registration.hpp
- src/modes.cpp
- src/modes/cuda/registration.cpp
- src/modes/hip/registration.cpp
- src/modes/metal/registration.cpp
- src/modes/opencl/registration.cpp
- src/modes/openmp/registration.cpp
- src/modes/serial/registration.cpp
> [Modes] Adding a getDeviceCount API to query number of available devices in an enabled mode

- include/occa/utils.hpp
- include/occa/utils/io.hpp
- src/occa/internal/io/fileOpener.cpp
- src/occa/internal/io/fileOpener.hpp
- src/occa/internal/io/utils.cpp
- src/utils/io.cpp
- tests/src/internal/io/fileOpener.cpp
Moved `exists` and `addLibraryPath`
> [Refactor] Moved some io methods to public API

- include/occa/experimental/array.hpp
- I forgot to add `linalg` to `experiemental`
> [Refactor] Add linalg to experimental

- include/occa/types/json.hpp
- src/types/json.cpp
> [Fix][JSON] Add explicit bool casting for {} json initializer

- src/occa/internal/lang/statement/ifStatement.cpp
> [Lang] Adding missing if statement condition to inner statement array

- include/occa/c/kernel.h
- src/c/kernel.cpp
- tests/src/c/kernel.cpp
Adds `occaKernelRunWithArgs` that takes an array
> [C] Adds occaKernelRunWithArgs

- include/occa.hpp
- include/occa/functional.hpp
- include/occa/functional/array.hpp
- include/occa/functional/range.hpp
- include/occa/functional/typelessArray.hpp
- include/occa/functional/types.hpp
- include/occa/functional/utils.hpp
- include/occa/loops.hpp
- src/functional/range.cpp
- src/functional/utils.cpp
- tests/src/functional/array.cpp
- tests/src/functional/range.cpp
- Splits base `array` functionality to `typelessArray`
- Implements `occa::range` with most `array` methods
Resolves #461
> [Loops] Adds occa::range

- .github/workflows/build.yml
- scripts/build/shellTools.sh
- src/occa/internal/lang/modes/oklForStatement.cpp
- src/occa/internal/lang/type/pointer.cpp
- src/occa/internal/lang/type/pointer.hpp
When checking for the okl-loop index, we missed checking the iterator for-loop.
Fixes #487
> [#487][Lang] Missed checking iterator for-loop statement

- src/occa/internal/modes/cuda/device.cpp
- src/occa/internal/modes/hip/device.cpp
- src/occa/internal/modes/serial/device.cpp
- tests/src/fortran/typedefs_helper.cpp
Redurect `stderr` to `stdout` and capture the output to print if compilation command fails
> [#188] Print compilation error

- examples/c/01_add_vectors/Makefile
- examples/c/02_background_device/Makefile
- examples/c/03_generic_inline_kernel/Makefile
- examples/c/04_reduction/Makefile
- examples/cpp/01_add_vectors/Makefile
- examples/cpp/02_for_loops/Makefile
- examples/cpp/03_arrays/Makefile
- examples/cpp/04_generic_inline_kernel/Makefile
- examples/cpp/05_custom_types/Makefile
- examples/cpp/06_shared_memory/Makefile
- examples/cpp/07_memory_management/Makefile
- examples/cpp/08_streams/Makefile
- examples/cpp/09_mpi/Makefile
- examples/cpp/10_native_cpp_kernels/Makefile
- examples/cpp/11_native_c_kernels/Makefile
- examples/cpp/12_native_cuda_kernels/Makefile
- examples/cpp/13_native_opencl_kernels/Makefile
- examples/cpp/14_openmp_interop/Makefile
- examples/cpp/15_cuda_interop/Makefile
- examples/cpp/16_finite_difference/Makefile
- examples/cpp/17_mandelbulb/Makefile
Set `@rpath` on MacOS, otherwise `lldb` freaks out when trying to debug an example
> [Examples] Set @.rpath

- src/occa/internal/lang/expr/dpcppAtomicNode.cpp
- src/occa/internal/lang/expr/dpcppLocalMemoryNode.cpp
- src/occa/internal/lang/expr/exprNode.hpp
- src/occa/internal/lang/modes/withLauncher.cpp
- src/occa/internal/modes/dpcpp/stream.cpp
PGI compiler is very opinionated about some things. Similar to #385.
> Fix PGI builds (needs newlines at EOF)

- src/occa/internal/modes/openmp/device.cpp
I have been building a binding library between Rust and Occa and ran into an issue when testing OpenMP that this PR fixes. There is probably a better way than this PR to do it. 
Essentially the compiler and subsequent OpenMP flags can be missed easily relative to a Serial device which can create strange behavior. In my case no OpenMP flags would be added by default which resulted in every kernel running in serial. Adding a compiler property to the device creation json wasn't very practical for general use with Rust binding to different c/cpp compilers.
> OpenMP corrected detection

- src/occa/internal/lang/loaders/typeLoader.cpp
This does not solve any real issues with missing features of the preprocessor, but the errors can be a bit more clear in the mean time.
> Improve occa preprocessor error messages

- src/occa/internal/lang/builtins/attributes/tile.cpp
> Change loop-bounds inequalities to strict inequalities for nested `@tile` loops.

- src/occa/internal/lang/modes/withLauncher.cpp
> Correctly detect last inner block when adding barriers

- .github/workflows/build.yml
- src/types/primitive.cpp
- tests/src/types/primitive.cpp
Disallow certain bitwise operations on `primitive` when the underlying value is bool.
> Patch primitive bitwise ops

- src/occa/internal/modes/cuda/device.cpp
- src/occa/internal/modes/cuda/kernel.cpp
- src/occa/internal/modes/hip/device.cpp
- src/occa/internal/modes/hip/registration.cpp
- src/occa/internal/modes/opencl/device.cpp
- src/occa/internal/modes/opencl/kernel.cpp
- src/occa/internal/modes/opencl/streamTag.cpp
- src/occa/internal/modes/opencl/utils.cpp
Noticed a few compiler warnings with gcc-11.
> Fix warnings with gcc-11

- src/occa/internal/core/kernel.cpp
> [Core] Kernel is no-op if either outer or inner dim is zero

- src/occa/internal/io/utils.cpp
- src/occa/internal/io/utils.hpp
- src/occa/internal/modes/cuda/device.cpp
- src/occa/internal/modes/dpcpp/device.cpp
- src/occa/internal/modes/hip/device.cpp
- src/occa/internal/modes/metal/device.cpp
- src/occa/internal/modes/opencl/utils.cpp
- src/occa/internal/modes/serial/device.cpp
- Rebases #520 onto [development](/libocca/occa/tree/development). 
- Closes #515
Co-authored-by: @stgeke 
Co-authored-by: @nnnunnn
> Update pr 520

- .github/workflows/build.yml
- CMakeLists.txt
- cmake/FindDPCPP.cmake
- configure-sycl-nv-cmake.sh
This PR proposes changes to the existing DPCPP configuration of OCCA to accommodate the support for running OCCA on Nvidia through SYCL 
Env Setup: [SYCL_NV_setup.txt](https://github.com/libocca/occa/files/10825754/SYCL_NV_setup.txt)
Env: [SYCL_NV_env.txt](https://github.com/libocca/occa/files/10825761/SYCL_NV_env.txt)
> OCCA configuration for supporting SYCL-on-Nvidia 

- src/occa/internal/modes/serial/device.cpp
> Sync kernel binary after staging has completed in serial mode.

- cmake/FindMETAL.cmake
Fixes https://github.com/libocca/occa/issues/667.
> fixed CMake whitespace issue

- README.md
- src/occa/internal/modes/hip/device.cpp
> [HIP] Bump supported HIP versions to v4.2 or later
