.travis.yml

I updated the travis build to using [address-sanitizer](https://code.google.com/p/address-sanitizer/) (which is available in gcc-4.9 and later).
It shows that there are some addressing issues and memory leaks in the occa library. Some of the leaks will grow with time, i.e., every time a kernel is called and/or new kernels is built/loaded.
You can preview the new travis output [here](https://travis-ci.org/jkozdon/occa)

Update travis to use address sanitizer

---

examples/addVectors/main.c
include/occa/cBase.hpp
scripts/setupKernelOperators.py
src/CUDA.cpp
src/OpenCL.cpp
src/cBase.cpp
src/operators/cKernelOperators.cpp

Here are some changes to (hopefully) fix memory leaks in OpenCL, CUDA, and the C bindings.  I can use the address sanitizer in gcc to test the changes to OpenCL and the C bindings but not for CUDA.

Fix memory leaks

---

include/occa/defines/CUDA.hpp

CUDA requires two arguments for hypot (not one like I originally put)

[Defines] fixing hypot for CUDA

---

include/occa/tools.hpp
src/Serial.cpp
src/tools.cpp

These changes align heap memory on OS X and add an environment variable `OCCA_HEAP_MEM_ALIGN` so the alignment can be specified at runtime.

Heap Alignment

---

.gitignore
examples/addVectors/ispc/ISPC.hpp
examples/addVectors/ispc/addVectors.ispc
examples/addVectors/ispc/addVectors.occa
examples/addVectors/ispc/main.cpp
examples/addVectors/ispc/makefile

This example has been cooked up by @inducer, @tcew, and myself to
demonstrate using ispc kernels.  Per the request by @dmed256 the
required tasksys.cpp file is not included in the occa source.
This also adds .occa kernel prototype for ispc backend.  More work is
needed to make this .occa file work with the OpenCL and CUDA backends.

Add ispc addVectors example

---

include/occa/CUDA.hpp
include/occa/HSA.hpp
include/occa/HSAV2.hpp
include/occa/OpenCL.hpp
include/occa/OpenMP.hpp
include/occa/Pthreads.hpp
include/occa/Serial.hpp
include/occa/base.hpp
src/CUDA.cpp
src/HSA.cpp
src/HSAV2.cpp
src/OpenCL.cpp
src/OpenMP.cpp
src/Pthreads.cpp
src/Serial.cpp
src/base.cpp
src/cBase.cpp

1. Added memory::detach() and memory::mappedDetach() methods that free the OCCA memory object without freeing the encapsulated device memory. This is a missing piece of OCCA interoperability for those cases when the user desires to recover and use the encapsulated device memory outside of OCCA without having to worry about scope or lifetime of the original OCCA memory object. Note the existing getMemoryHandle() method is used to access the encapsulated device memory before detaching.
2. Added some doxygen comments in header files. In particular, added description for memory::getMemoryHandle() to document what is actually returned for various OCCA devices, in order to facilitate the interoperability scenario.
3. Fixed problem with nonsense CPU frequency value displayed by occainfo on …

Detach methods for OCCA memory objects

---

src/base.cpp

Mapped allocations don't use device memory, so we will not count them
with the device memory counter.

Don't count mapped allocations

---

scripts/compilerVendorTest.cpp

This commit adds support for returning OCCA_IBM_VENDOR when compiling with newer versions of the XL compiler.

Detect new versions of XL compiler

---

include/occa/defines/vector.hpp
scripts/setupVectorDefines.py

Previously when compiling with -Wall vector.hpp would generate a large number of
warnings of the form:
```
occa/include/occa/defines/vector.hpp:1461:9: warning: ‘*’ in boolean context, suggest ‘&&’ instead [-Wint-in-bool-context]
a.s15 *= b.s15;
```
This commit silences those warnings using GCC pragmas which will work with both
GCC and the mpic/mpic++ compilers.

Silence warnings about multiplying bools

---

scripts/shellTools.sh

Arch Linux (and possibly other Linux distros) put all the CUDA files in `/opt/cuda`, so add those to the list.

Add /opt/cuda to include and library search paths

---

src/tools/env.cpp

SIGKILL cannot be caught so there is no point attempting to register
actions, which generates warnings in certain environments, such as
Valgrind:
==31674== Warning: ignored attempt to set SIGKILL handler in sigaction();
==31674==          the SIGKILL signal is uncatchable

initSignalHandling: do not attempt to catch SIGKILL

---

Makefile

Fixes rebuilding include/occa/defines/compiledDefines.hpp
- [x ] Nothing got committed into `./lib` and `./obj`
- [ x] MIT License copyright in new files

Makefile: fix shell diff

---

include/occa/tools/string.hpp

Small bug fix: XL compiler requires user to include cstdlib for system atof().

XL compiler requires user to include cstdlib for system atof()

---

src/lang/modes/opencl.cpp

Fixed an issue where my recent change to the OpenCL parser was mistakenly migrating statements. The old code searched for variable declarations with the "shared" in a kernel function and migrated them to the top of the kernel. However this would mistakenly migrate statements like 
`double r_q = s_q[i];`
when `s_q` was a shared array. This patch now checks if the variables being declared in the statement have the "shared" attribute themselves before migrating.

[Parser] Fixed register variables being migrated in OpenCL mode

---

Makefile
scripts/Makefile

- Expand makefile variables to speedup the build.
- Add makefile target `info` that shows the build configuration without performing the build - this is useful for tweaking the configuration before building.
- A few minor additions/tweaks in the Makefile.

A few improvements in the Makefile

---

include/occa/mode/hip/device.hpp
include/occa/mode/hip/memory.hpp
include/occa/mode/hip/utils.hpp
src/mode/hip/device.cpp
src/mode/hip/kernel.cpp
src/mode/hip/registration.cpp
src/mode/hip/utils.cpp

- Fixed a subtle issue where HIP expects packed kernel arguments to be byte-aligned. 
- Added a target architecture, e.g. '-t gfx900' compiler flag to the hipcc calls to speed up kernel compilation and reduce binary sizes. 
- Forwarded changed to getMappedPtr to HIP backend.

[HIP] Fixes to HIP backend. 

---

include/occa/modes/hip/device.hpp
include/occa/modes/hip/kernel.hpp
include/occa/modes/hip/memory.hpp
include/occa/modes/hip/stream.hpp
include/occa/modes/hip/streamTag.hpp
include/occa/modes/hip/utils.hpp
scripts/Makefile
src/modes/hip/device.cpp
src/modes/hip/kernel.cpp
src/modes/hip/memory.cpp
src/modes/hip/stream.cpp
src/modes/hip/streamTag.cpp
src/modes/hip/utils.cpp
src/modes/opencl/device.cpp

Updating the HIP backend to be in sync with CUDA backend support. Also added an OpenCL v2.0 check to avoid using deprecated `clCreateCommandQueue` (AMD's OpenCL complains about this). 
Side note: While testing the  @ restrict keyword in OpenCL mode, I noticed both Nvidia and AMD targets seem to want the restrict key word to be `__restrict__`, which means I had to change [line 21 of src/lang/modes/opencl.cpp](https://github.com/libocca/occa/blob/022b76829d43cbe20b719e6d5a54c9aff8fa178c/src/lang/modes/opencl.cpp#L21). I'm not sure if other platforms also need this keyword so I haven't included that change.

[HIP/OpenCL] Updates for HIP backend and updating deprecated OpenCL APIs

---

include/occa/core/device.hpp
include/occa/core/kernel.hpp
include/occa/core/launchedDevice.hpp
include/occa/core/launchedKernel.hpp
include/occa/defines/occa.hpp
include/occa/lang/kernelMetadata.hpp
include/occa/lang/parser.hpp
include/occa/lang/preprocessor.hpp
include/occa/modes/cuda/device.hpp
include/occa/modes/hip/device.hpp
include/occa/modes/metal/device.hpp
include/occa/modes/opencl/device.hpp
include/occa/modes/openmp/device.hpp
include/occa/modes/serial/device.hpp
include/occa/modes/serial/kernel.hpp
src/core/device.cpp
src/core/kernel.cpp
src/core/kernelBuilder.cpp
src/core/launchedDevice.cpp
src/core/launchedKernel.cpp
src/lang/kernelMetadata.cpp
src/lang/parser.cpp
src/lang/preprocessor.cpp
src/modes/cuda/device.cpp
src/modes/hip/device.cpp
src/modes/metal/device.cpp
src/modes/opencl/device.cpp
src/modes/openmp/device.cpp
src/modes/serial/device.cpp
src/modes/serial/kernel.cpp

The `build.json` file now stores a map from a kernel's dependency which comes from a `#include` and its file content hash. 
The first time a kernel is build, the hash comes from the file source. Consecutive builds will check if the dependencies changed. If they did, the new hash comes from a combination of the kernel source and dependency hashes.
This change is still missing tests

#236 Hash kernel dependencies

---

include/occa/scripts/shellTools.sh

Copy bin, include, lib into PREFIX/ when installing.

Copy to prefix instead of prefix/subfolder

---

Makefile
include/occa/lang/preprocessor.hpp
include/occa/lang/tokenizer.hpp
src/lang/macro.cpp
src/lang/preprocessor.cpp
src/lang/tokenizer.cpp
tests/src/lang/preprocessor.cpp

When using stringification macros such as `OCCA_JIT`, there is no way to add preprocessor directives such as
```
OCCA_JIT(
props,
(entries, a, b, ab),
(
for (int block = 0; block < entries; block += 16; @outer) {
#pragma ivdep
for (int i = block; i < (block + 16); ++i; @inner) {
...
}
}
)
)
```
Introducing `@directive` which replaces
```
#pragma ivdep
```
with
```
@directive("#pragma ivdep")
```
resulting in the code looking like:
```
OCCA_JIT(
props,
(entries, a, b, ab),
(
for (int block = 0; block < entries; block += 16; @outer) {
@directive("#pragma ivdep")
for (int i = block; i < (block + 16); ++i; @inner) {
...
}
}
)
)
```

[OKL] Adds @directive preprocessor attribute

---

include/occa/tools/json.hpp
include/occa/tools/properties.hpp
src/tools/json.cpp
src/tools/properties.cpp

```bash
valgrind -v --leak-check=full --show-leak-kinds=all --suppressions=<path/to/conf>
```
Add the ` --gen-suppressions=all` flag to your `valgrind` command
`dlopen` ends up allocating some thread-local storage memory
Link:
- https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=700899
Suppression:
```conf
{
dlopen_leaks
Memcheck:Leak
fun:calloc
fun:_dlerror_run
fun:*dlopen*
...
}
```
Some allocations are not cleaned up by OpenMP even when not using them
```conf
{
openmp_leaks
Memcheck:Param
sched_setaffinity(mask)
fun:syscall
...
obj:*lib*omp*
...
}
{
openmp_leaks
Memcheck:Leak
fun:*alloc
...
obj:*lib*omp*
...
}
```
Useful suppressions that Valgrind doesn't detect
```conf
{
alloc_libcuda
Memcheck:Leak
match-leak-kinds: definite,indirect,possible,reachable
fun:*alloc
...
obj:*libcuda.so* …
```

[Valgrind] Removed bad access to json.initialized

---

src/core/memory.cpp
src/modes/serial/device.cpp

```cpp
int *ptr = new int[10];
occa::memory mem_doesnt_deallocates_ptr = occa::malloc<int>(
10,
ptr,
"use_host_pointer: true"
)
occa::memory mem_deallocates_ptr = occa::malloc<int>(
10,
ptr,
"use_host_pointer: true, "
"own_host_pointer: true"
)
```

[Memory] Adds own_host_pointer flag to malloc and wrapMemory

---

include/occa/core/base.hpp
include/occa/core/base.tpp
src/core/base.cpp
tests/src/core/memory.cpp

The new default `void` mallloc ended up trying to allocate 0 bytes since 
```cpp
dtype::get<void>() == 0
```

[BG] Fixes <void> templated malloc

---

include/occa/tools.hpp
include/occa/tools/string.hpp
include/occa/tools/sys.hpp
include/occa/tools/vector.hpp
src/modes/serial/device.cpp
src/tools/string.cpp
src/tools/sys.cpp
src/tools/vector.cpp
tests/src/tools/vector.cpp

After updating OCCA to use C++11, I forgot to update Serial kernel compilations to use C++11 headers since they `#include <occa.hpp>`

[Serial] Fixes lack of C++11 flags when compiling kernels

---

config.default.json
include/occa/modes/hip/memory.hpp
include/occa/modes/hip/polyfill.hpp
include/occa/modes/hip/utils.hpp
scripts/Makefile
src/modes/hip/device.cpp
src/modes/hip/memory.cpp
src/modes/hip/registration.cpp
src/modes/hip/utils.cpp

Adds some fixes provided by @noelchalmers to help support HIP-NVCC

[HIP] Adds support for hip-nvcc (Thanks @noelchalmers!)

---

include/occa/core/kernelArg.hpp
src/core/kernel.cpp
src/core/kernelArg.cpp
tests/files/argKernel.okl
tests/src/core/kernel.cpp

#235 `occa::null` can be passed to kernels as a way to omit an `occa::memory` argument

[Kernel] Adds occa::null

---

include/occa/lang/preprocessor.hpp
src/lang/preprocessor.cpp

The following was failing since the first `@directive` set the reading status to `ignore`, avoiding reading following `@directive` to stop the `#if`
```cpp
@directive("#if true")
// ...
@directive("#else")
// ...
@directive("#endif")
```

[Preprocessor] Fixes loading @ directive inside #if/#else statements

---

include/occa/core/kernelArg.hpp
include/occa/core/memory.hpp
src/core/kernelArg.cpp
src/core/memory.cpp

`occa::null` is of type `occa::memory` to avoid casting issues. Same as uninitialized `occa::memory` objects, but more descriptive in its use.

[OCCA] Uninitialized memory passed as null

---

src/modes/cuda/memory.cpp
src/modes/hip/memory.cpp
src/modes/metal/memory.cpp
src/modes/opencl/memory.cpp
src/modes/serial/memory.cpp

OpenCL wasn't considering `isOrigin` when reference counting with slices (Thanks @stgeke!)

[Core] Fix memory reference double-free with slices

---

src/modes/openmp/device.cpp

Small change to inject information about using an OpenMP device when generating kernel hash. Without this, the same kernel hash is generated in both Serial and OpenMP modes and cached kernels are incorrectly found.

[OpenMP] Avoid generating same kernel hash as Serial mode

---

src/lang/modes/cuda.cpp

Global `const` statements are replaced with `__constant__` memory. This shouldn't be the case for `typedefs`
```cpp
typedef const void* const_void
```
shouldn't be translated to
```cpp
typedef __constant__ void* const_void
```

[OKL][CUDA] Fixes const -> __constant__ replacement on typedef statements

---

include/occa/tools/gc.hpp
include/occa/tools/gc.tpp
src/core/kernel.cpp
src/core/kernelBuilder.cpp
src/core/launchedDevice.cpp
src/core/launchedKernel.cpp
src/modes/cuda/device.cpp
src/modes/hip/device.cpp
src/modes/metal/device.cpp
src/modes/opencl/device.cpp

- Internal kernels on launched kernels (launcher + device kernels) shouldn't attach their refs to the device since the launched kernel will delete them in its destructor

[GC] Fixes refs on launched kernels

---

include/occa/modes/cuda/device.hpp
src/core/kernelArg.cpp
src/modes/cuda/device.cpp
src/modes/cuda/kernel.cpp

CUDA doesn't accept `NULL` pointers as kernel arguments (even if they are not used). We let the device allocate and reuse a 1 byte array to use as a fake NULL pointer.

[CUDA] Adds pseudo-NULL pointer

---

include/occa/c/types.hpp
src/c/kernel.cpp
src/c/types.cpp
tests/files/argKernel.okl
tests/src/c/kernel.cpp

- Just like we can pass `occa::null` to kernels in the C++ API, allow `occaNull` to be passed to kernels in the C API

[C] Allows occaNull to be passed to kernels

---

include/occa/lang/macro.hpp
include/occa/lang/preprocessor.hpp
src/lang/macro.cpp
src/lang/preprocessor.cpp
tests/src/lang/preprocessor.cpp

```c
#define ONE 1
#define TWO 2
#define ONE_TWO_FUNC(FUNC) FUNC ## _ ## ONE ## _ ## TWO
ONE_TWO_FUNC(hi)
```
was being expanded to
```
hi_ONE_TWO
```
instead of
```
hi_1_2
```

[Preprocessor] Stringifies tokens inside concat

---

examples/cpp/17_opencl_interop/main.cpp

Fix include path in examples/cpp/17_opencl_interop/main.cpp

Fix typo in include path

---

src/lang/macro.cpp
tests/src/lang/preprocessor.cpp

Fixes nested-parentheses in macro arguments
```cpp
#define J2(A1, A2, A3) A1 A2 A3
#define J1(A1) J2(A1, (1, 2), ((3), (4)))
J1(0)
```

[Preprocessor] Handles nested parentheses when reading arguments

---

tests/run_examples

Fixes these issues from Travis CI on MacOS tests
```
dyld: Library not loaded: @rpath/libocca.dylib
Referenced from: <OCCA_DIR>/examples/cpp/02_background_device/./main
Reason: image not found
```

[Test] Fix @rpath issues with MacOS tests

---

include/occa/modes/cuda/device.hpp
include/occa/tools/env.hpp
include/occa/tools/sys.hpp
src/lang/preprocessor.cpp
src/modes/cuda/device.cpp
src/modes/serial/device.cpp
src/tools/env.cpp
src/tools/sys.cpp

OKL kernels will now also look at `OCCA_INCLUDE_PATH` to find `#include` directories
Native kernels will add `-I` for each passed in `OCCA_INCLUDE_PATH` as well as `-L` for each passed in `OCCA_LIBRARY_PATH`
```
> OCCA_INCLUDE_PATH="i1:i2:i3" OCCA_LIBRARY_PATH="l1:l2:l3"  a -v
Compiling [addVectors]
nvcc -O3 -arch=sm_61 -Ii1 -Ii2 -Ii3 -Ll1 -Ll2 -Ll3 ...
```

[Core] Add support for OCCA_INCLUDE_PATH and OCCA_LIBRARY_PATH

---

include/occa/c/types.h
src/c/types.cpp

Use `bool` from `stdbool.h` for boolean types. 
This header was introduced in C99, for more details see:
https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/stdbool.h.html
I tested this change by running the C examples, which use this functionality. All work as expected.

[C] Use bool from stdbool.h for boolean types

---

CMakeLists.txt
cmake/SetCompilerFlags.cmake
src/CMakeLists.txt

Attempts to fix #320:
* Set the C++11 standard globally.
* Same for no C++11 extensions.
* Add functions to test if flags are accepted by the compiler and add only those that are.
* Add more warning flags.
Although I have automated tests set up for clang / gnu / Intel I only use Linux, so maybe @JamesEggleton can check if this works for him on MacOS?

[CMake] Let CMake determine which compiler flags should / can be used

---

examples/c/01_add_vectors/main.c
examples/c/02_background_device/main.c
examples/c/03_inline_okl/main.c
examples/c/04_reduction/main.c
include/occa/c/types.h
src/c/types.cpp
tests/run_examples
tests/src/c/base.cpp
tests/src/c/device.cpp
tests/src/c/dtype.cpp
tests/src/c/json.cpp
tests/src/c/kernel.cpp
tests/src/c/memory.cpp
tests/src/c/properties.cpp
tests/src/c/types.cpp

`occaFree` used to take an `occaType` argument by value which didn't properly set the magic headers to `undefined` afterwards. This changes the function signature from
```c
void occaFree(occaType value);
```
->
```c
void occaFree(occaType *value);
```

[C] Update occaFree

---

src/tools/sys.cpp
tests/src/tools/sys.cpp

A path is now considered safe to remove if any component of
it is 'occa' or '.occa', and if the final depth > 1.
Attempts to fix #326 .

[Core] Tweak behaviour of isSafeToRmrf

---

scripts/Makefile

This PR fixes
- check for HIP installation even if OCCA_HIP_ENABLED is not defined
- in case default_path doesn’t exists backfall to HIP_PATH if OCCA_HIP_ENABLED = 1

[Build][HIP] Fix HIP compilation issues

---

include/occa/c/json.h
src/c/json.cpp

This is a follow-up of PR #318 to flip a couple of functions from using `int` instead of `bool` in the json interface.

[C] Use bool instead of int in json interface

---

scripts/Makefile

This fixes the compiler flags for OpenMP in case `OCCA_OPENMP_ENABLED` was specified explicitly. Previously, the following would fail with a linker errror:
``` sh
make OCCA_OPENMP_ENABLED=1
```

[Build] Fix compiler flags for OpenMP

---

include/occa/c/types.h
src/c/types.cpp

This adds the two global variables `occaTrue` and `occaFalse` to the C API.

[C] Add occaTrue and occaFalse

---

Makefile
examples/c/01_add_vectors/Makefile
examples/c/02_background_device/Makefile
examples/c/03_inline_okl/Makefile
examples/c/04_reduction/Makefile
examples/cpp/01_add_vectors/Makefile
examples/cpp/02_background_device/Makefile
examples/cpp/03_inline_okl/Makefile
examples/cpp/04_reduction/Makefile
examples/cpp/05_building_kernels/Makefile
examples/cpp/06_unified_memory/Makefile
examples/cpp/07_dtypes/Makefile
examples/cpp/08_arrays/Makefile
examples/cpp/09_streams/Makefile
examples/cpp/10_mpi/Makefile
examples/cpp/11_native_cpp_kernels/Makefile
examples/cpp/12_native_c_kernels/Makefile
examples/cpp/13_native_cuda_kernels/Makefile
examples/cpp/14_native_opencl_kernels/Makefile
examples/cpp/15_openmp_interop/Makefile
examples/cpp/16_cuda_interop/Makefile
examples/cpp/17_opencl_interop/Makefile
examples/cpp/18_finite_difference/Makefile
examples/cpp/19_mandelbulb/Makefile
scripts/Makefile

The `paths` variable (defined in `scripts/Makefile`) did not include `-L$(OCCA_DIR)/lib` and the logic around including `-I$(incPath)` was broken. The former issue was especially confusing given the comments in the project [`Makefile`](https://github.com/libocca/occa/blob/f906041240eb36e51b80ba542682975314db03a4/Makefile#L26)
This PR fixes both issues and modifies the project and example Makefiles accordingly. 
All tests passed on my local machine (Fedora Linux using GCC 9).

[Build] Clean paths variable in Makefiles

---

.github/workflows/build.yml
Makefile
include/occa/scripts/shellTools.sh
scripts/Makefile

This PR adds the `-march=native` option to the GCC/LLVM flags, similar to the options for INTEL, PGI, PATHSCALE, and others. This supersedes PR #334 and contains a proper workaround for the CI tests on Ubuntu using GCC.
This also includes minor changes in order to print out the compiler vendor in the CI tests, and contains further a fix for the MacOS runs with GCC.

[Build][CI] Add -march=native for gcc and fix CI tests

---

include/occa/io/utils.hpp
include/occa/lang/preprocessor.hpp
src/io/utils.cpp
src/lang/preprocessor.cpp
src/tools/sys.cpp
tests/src/fortran/typedefs_helper.cpp
tests/src/io/fileOpener.cpp
tests/src/io/utils.cpp
tests/src/lang/preprocessor.cpp
tests/src/tools/sys.cpp

Allows including standard headers such as 
```cpp
#include <math.h>
```
but prints warnings since it might not be portable
For cleanup, adds `occa_` and `.occa_` prefixed files to the list of "safe to delete" directories

[Preprocessor] Allows including standard headers (prints warnings)

---

src/lang/preprocessor.cpp
tests/src/lang/preprocessor.cpp

Adds the following defines when compiling OKL kernels:
- `OCCA_MAJOR_VERSION`
- `OCCA_MINOR_VERSION`
- `OCCA_PATCH_VERSION`
- `OCCA_VERSION`
- `OKL_VERSION`
- `__OKL__`
- `__OCCA__`
All of these defines can be found in `include/occa/defines/occa.hpp` except for the following which are defined as a plain `1` to be truthy:
- `__OKL__`
- `__OCCA__`

[Preprocessor] Adds OCCA defines when compiling kernels

---

include/occa/lang/expr/exprNode.hpp
include/occa/lang/printer.hpp
src/lang/expr/callNode.cpp
src/lang/expr/expression.cpp
src/lang/expr/tupleNode.cpp
src/lang/printer.cpp

Pretty prints long function calls and tuples
```cpp
tensor_2d_gradElementTranspose_Q6_P5(o0_B, o0_Bx, (double *) quadOutput0[component][0], (double *) quadOutput0[component][1], &dofOutput0[0 + (5 * (0 + (5 * (component + (1 * element)))))]); 
```
⟶
```cpp
tensor_2d_gradElementTranspose_Q6_P5(
o0_B,
o0_Bx,
(double *) quadOutput0[component][0],
(double *) quadOutput0[component][1],
&dofOutput0[0 + (5 * (0 + (5 * (component + (1 * element)))))]
);
```
```cpp
const double dXdxdXdxT[2][2] = {{qdata[i + 0 * Q], qdata[i + 2 * Q]}, {qdata[i + 2 * Q], qdata[i + 1 * Q]}};
```
⟶
```cpp
const double dXdxdXdxT[2][2] = {
{qdata[i + 0 * Q], qdata[i + 2 * Q]},
{qdata[i + 2 * Q], qdata[i + 1 * Q]}
};
```

[Lang] Pretty-prints long function calls and tuples

---

include/occa/lang/printer.hpp
include/occa/lang/token/commentToken.hpp

Using the default `printer` re-read its contents, making the `charsFromNewline` too big due to repeating the same line over and over

[Parser] Cleans up output indentation when using a buffer

---

include/occa/lang/preprocessor.hpp
src/lang/preprocessor.cpp
tests/src/lang/preprocessor.cpp

Adds `OKL_KERNEL_HASH` string define to make it easy to debug which kernel is being run
**Tip**: You can use `printf()` or `std::cout` in Serial mode!

[Preprocessor] Adds OKL_KERNEL_HASH define to help debug running kernels

---

src/lang/parser.cpp
tests/files/addVectors.okl

During the PR to add `commentStatement`, the logic for fetching the next non-`commentStatement` when it started with a `commentStatement` was wrong

[Parser] Bug not loading child statements properly

---

include/occa/c/types.h
include/occa/c/types.hpp
include/occa/lang/parser.hpp
include/occa/lang/tokenContext.hpp
src/c/types.cpp
src/lang/parser.cpp
src/lang/statementPeeker.cpp
src/lang/tokenContext.cpp
tests/files/addVectors.okl
tests/src/io/lock.cpp
tests/src/lang/tokenContext.cpp

Removes `comment` tokens from `tokenContext_t` to avoid parsing issues

[Parser] tokenContext auto-removes certain tokens

---

include/occa/lang/preprocessor.hpp
include/occa/lang/processingStages.hpp
include/occa/lang/stream.hpp
include/occa/lang/stream.tpp
src/lang/parser.cpp
src/lang/preprocessor.cpp
src/lang/processingStages.cpp

Bug #311 was caused by stream caching. Places were the code rewinds (`#include`) clears the cache now.

[Lang] Adds stream cache clearning to fix #311

---

src/lang/tokenizer.cpp
tests/src/lang/tokenizer/token.cpp

Fixes corner-case when loading tokens and the identifier starts with `true` or `false`

[Tokenizer] Don't prematurely load primitives

---

include/occa/lang/file.hpp
src/lang/file.cpp
src/lang/statement/declarationStatement.cpp
src/lang/statement/functionDeclStatement.cpp
src/lang/type/vartype.cpp

New struct loader wasn't handling when `struct` was used as a qualifier

[Parser] Properly stores struct definitions

---

CMakeLists.txt
src/modes/cuda/device.cpp
src/modes/hip/device.cpp
src/modes/serial/device.cpp

This PR is to move the install location of the `compiledDefines.hpp` header to the cmake build folder, rather than placing it in the OCCA_DIR/include folder. This behavior makes the cmake build system align better with the usual cmake workflow.

[CMake] Place compiledDefines header in Cmake build directory, rather than source tree. 

---

.github/workflows/build.yml
bin/occa.cpp
include/occa/modes.hpp
src/core/base.cpp
src/modes.cpp
tests/src/modes.cpp

Made modes case-insensitive since it shouldn't matter for the user if they use `"CUDA"` or `"cuda"`

[Core] Allows for case-insensitive mode names

---

src/modes/cuda/device.cpp
src/modes/hip/device.cpp
src/modes/opencl/device.cpp
src/modes/serial/device.cpp

It would be nice to give priority to environment variables; it can prevent recompilation of large and deployed applications.

Use env variables then compiled user ones and finally hardcoded ones

---

src/modes/cuda/utils.cpp

Another small thing: assigning a negative literal to size_t is causing compiler complains.
We had this discussion before about udim_t and we added `const occa::udim_t UDIM_DEFAULT = static_cast<occa::udim_t>(-1);` for that to avoid `static_cast` noise everywhere, but since `size_t` is a default type I'm not sure if we would want to go that way? Plus, it's not really a 'default'.
In this particular instance, an error should be thrown if anything is wrong, right? So initializing with 0 is as good as anything?

Fix assignment of negative literal to unsigned type

---

bin/occa.cpp
include/occa/io/utils.hpp
include/occa/tools/env.hpp
src/core/device.cpp
src/io/utils.cpp
src/lang/preprocessor.cpp
src/tools/env.cpp

It would be quite useful to us to be able to specify paths where occa can look for kernels that are specified with a relative path.
It should work in the expected way: if a path is absolute, that path is taken regardless of anything else, if it is relative, all the paths in OCCA_KERNEL_PATH (colon-separated) will be checked and if it's still not found the cwd is used.
Similar code already existed in the preprocessor, and I've lifted this into a function.

Add OCCA_KERNEL_PATH

---

include/occa/lang/builtins/types.hpp
src/lang/builtins/types.cpp
src/lang/keyword.cpp
tests/src/lang/type.cpp

Currently the parser/preprocessor doesn't handle the `size_t` and `ptrdiff_t` types. I added them in the same places where `wchar_t` was handled to follow the example of another type that doesn't do much.
Should I add/extend a test for this, if this is a sensible addition at all?

Add size_t and ptrdiff_t to builtin types

---

include/occa/defines/errors.hpp
include/occa/modes/cuda/utils.hpp
src/modes/cuda/device.cpp
src/modes/cuda/kernel.cpp
src/modes/cuda/memory.cpp
src/modes/cuda/stream.cpp
src/modes/cuda/streamTag.cpp
src/modes/cuda/utils.cpp

CUDA uninitializes before some static objects are destroyed, raising some `CUDA_ERROR_DEINITIALIZED`. Since this is most likely going to show up on destructors at the end of a program, we add a special case to avoid erroring out.

[CUDA] Removes certain errors on destructors due to CUDA Deinit

---

include/occa/scripts/shellTools.sh
include/occa/scripts/tests/compiler.cpp

On PowerPC (e.g. [Lassen](https://hpc.llnl.gov/hardware/platforms/lassen)) `-march` is not a valid flag of gcc and compilation fails right away. This adds a check for PowerPC (gcc defines `__powerpc__` there) and replaces `-march=native` with `-mcpu=native -mtune=native` in that case.
If this is not the right place to do this change please let me know!

Fix compilation on PowerPC

---

include/occa/tools/sys.hpp
src/tools/sys.cpp

@dmed256, I think this *might* fix the libCEED + OCCA PowerPC issue we see on our Travis, but I don't know enough about OCCA to know if there are other places where similar changes need to occur.
I didn't see your yml, but I know in the past you used Travis. If you're still using Travis,you can now test on various hardware: https://docs.travis-ci.com/user/multi-cpu-architectures/
Closes #394

Sys - add PPC for compiler flag detection

---

src/modes/openmp/utils.cpp

This should be the second half of #395. Now we pass with the new OCCA backend on Travis PowerPC:
https://travis-ci.com/github/CEED/libCEED/jobs/372904963

OpenMP - add base compiler flag for OpenMP on PPC with GCC

---

include/occa/modes/cuda/device.hpp
src/modes/cuda/device.cpp
src/modes/cuda/kernel.cpp

If multiple devices are created in the same process, the wrong context gets kept in a few places.

[CUDA] Sets the CUDA context in more methods

---

include/occa/lang/preprocessor.hpp
include/occa/lang/tokenizer.hpp
src/lang/preprocessor.cpp
src/lang/tokenizer.cpp
tests/src/lang/preprocessor.cpp
tests/src/lang/tokenizer/token.cpp

Adds the option to include non-standard system headers
```sh
> occa translate addVectors.okl
addVectors.okl:1:2: Error: File does not exist
#include "foobar"
^
```
Adding 
```cpp
kernelProps["okl/strict_headers"] = false;
```
or passing it in the CLI ends up including headers even if OCCA can't find them:
```sh
> occa translate -k "okl: { strict_headers: false }" addVectors.okl
...
#include "foobar"
...
```

[Lang][Preprocessor] Adds okl/strict_headers option

---

src/bin/occa.cpp

The occa executable reports a bunch of stuff, but not (yet) `OCCA_MPI_ENABLED`. This PR adds that.

[CLI] Report OCCA_MPI_ENABLED

---

tests/src/lang/CMakeLists.txt

With recent commits a directory was removed and another one renamed, and this fixes CMake to use the right dirs again.

[CMake] Fix changed subdirs in tests

---

src/lang/expr/expressionParser.cpp
src/lang/modes/oklForStatement.cpp

The Intel compiler complains about shadowing some variables. This PR fixes them in a way similar to 3e56817e9ab141068853130caab88a7263273b08 (adding underscores).

[Fix] shadowing warnings

---

include/occa/lang/primitive.hpp
src/lang/primitive.cpp
tests/src/lang/primitive.cpp

Examples of cases covered now:
```
0x7f800000U
0x7f800000L
0x7f800000LL
0x7f800000UL
0x7f800000LLU
```
This also outputs primitives based on their source rather than parsed values for better accuracy

[Lang] Adds support for U/L/LL suffix on hex/binary primitives

---

include/occa/tools/env.hpp
src/tools/env.cpp

Adds a programmatic way of setting the `OCCA_CACHE_DIR`
```cpp
occa::env::setOccaCacheDir(<path>)
```
Solves #252

[QOL] Adds occa::env::setOccaCacheDir

---

scripts/Makefile

From ROCm 4.0, hipconfig --platform will output 'amd' instead of 'hcc'.
This change simply proactively mitigates a potential surprise where OCCA
thinks it couldn't find ROCm.

Make build system understand new hipconfig output

---

src/modes/hip/utils.cpp

Since hipGetDeviceCount will throw a hipErrorNoDevice error when no devices are present, it's better to not check the error code so that `occa info` does not fail on GPU-less headnodes.

[HIP] Avoid checking the error code from hipGetDeviceCount

---

include/occa/core/kernel.hpp
include/occa/types/dim.hpp
src/core/kernel.cpp
src/types/dim.cpp

If the outer and inner dims are all set to `0`, avoid launching the kernel

[#396] Avoids kernel calls on noop dim sizes

---

include/occa/lang/modes/withLauncher.hpp
src/lang/modes/withLauncher.cpp

Fixes a bug where inner for loops were being replaced while checking if they were the outermost inner loop. Also adds one additional check for whether the inner block is the last in a kernel and skips adding a barrier if so.
Fixes #205

[Lang] Add barriers only after last inner block in each kernel, skipping last inner block

---

include/occa/core/base.hpp
src/core/base.cpp
src/occa/internal/modes.cpp
src/occa/internal/modes.hpp

Accidentally moved the `modeIsEnabled` method into `internals`. Moving it back to making it publicly available

[Refactor] Move modeIsEnabled back to public API

---

src/occa/internal/modes/hip/memory.cpp
src/occa/internal/modes/hip/memory.hpp

`modeMemory_t` has a `ptr` field so backends don't have to implement the `ptr()` method. This has led to some pointer reference hackery we should probably remove in the future :sweat_smile:

[HIP] Update ptr ref hackery

---

examples/cpp/10_mpi/main.cpp
src/mpi.cpp

After the recent reshuffle these mpi headers were moved, but not corrected at their use sites.

[Fix] Use correct new path for expermental mpi.hpp

---

tests/CMakeLists.txt

One of the Fortran tests is weird in that it uses a cpp file as a library.
This file should *not* be used to build a standalone executable, but built as a library and then linked to the one test that uses it.
Perhaps there is a nicer way to fix this (the current commit is a bit ad-hoc), but as it stands it spits out linker errors if I build with `ENABLE_FORTRAN = ON` so it does need some attention.

[Fix] Add exception for one Fortran test that doesn't fit the standard CMake functions

---

src/occa/internal/modes/hip/kernel.cpp

I didn't realize HIP was copying the raw pointer and not the pointer value

[HIP] Fix the way hip sets arguments, I broke it on #438

---

include/occa/core/base.hpp
src/core/base.cpp

I noticed the device::setup syntax when passing a string has subtly changed from `device.setup("mode: 'Serial'")` to `device.setup("{mode: 'Serial'}")`. Forwarding that syntax change to the getDeviceCount API.

[Core] Make getDeviceCount syntax match new device::setup syntax

---

src/occa/internal/io/utils.cpp
src/occa/internal/io/utils.hpp

The cached `cachePath()` was making any updates to `OCCA_CACHE_PATH` noop
Fixes #450

[#450][IO] Don't cache the cache path

---

src/occa/internal/modes/opencl/polyfill.hpp

[OpenCL] Define CL_TARGET_OPENCL_VERSION

---

src/occa/internal/modes/cuda/device.cpp
src/occa/internal/modes/cuda/polyfill.hpp

We haven't seen any benefit from creating our own context. If anything, it makes interoperability with OCCA a lot harder.
Fixes #224

[CUDA] Always use the primary context

---

src/occa/internal/modes/opencl/utils.cpp

Similar to #426, AMD's OpenCL will throw a `CL_DEVICE_NOT_FOUND` on checking the deviceIDs on GPU-less head nodes. This PR avoids checking the error code returned when getting device counts, which avoids `occa info` failing on head nodes.

[OpenCL] Avoid checking the error code in getDeviceCountInPlatform

---

src/occa/internal/modes/hip/polyfill.hpp
src/occa/internal/modes/hip/utils.cpp

HIP added a gcnArchName member to the hipDeviceProps_t struct.  This is
a char array and is more suitable for determining the name of the
architecture to target.  The older gcnArch is an integer and is a little
more brittle.

Use arch name property to determine gpu arch

---

include/occa/functional/array.hpp
tests/src/functional/array.cpp

Adds more `occa::array` methods
- `dotProduct`
- `clamp`
- `clampMin`
- `clampMax`

[Array] Adds dotProduct and clamp

---

include/occa/c/memory.h
include/occa/core/memory.hpp
include/occa/core/memory.tpp
src/c/memory.cpp
src/core/memory.cpp
src/occa/internal/core/memory.cpp
src/occa/internal/core/memory.hpp
src/occa/internal/modes/cuda/device.cpp
src/occa/internal/modes/cuda/device.hpp
src/occa/internal/modes/cuda/memory.cpp
src/occa/internal/modes/cuda/memory.hpp
src/occa/internal/modes/hip/device.cpp
src/occa/internal/modes/hip/device.hpp
src/occa/internal/modes/hip/memory.cpp
src/occa/internal/modes/hip/memory.hpp
src/occa/internal/modes/metal/memory.cpp
src/occa/internal/modes/metal/memory.hpp
src/occa/internal/modes/opencl/device.cpp
src/occa/internal/modes/opencl/device.hpp
src/occa/internal/modes/opencl/memory.cpp
src/occa/internal/modes/opencl/memory.hpp
tests/src/c/device.cpp
tests/src/c/memory.cpp

~~This PR implements a new API, `hostMalloc` which lets users malloc `occa::memory` regions in pinned host memory, if the backend device supports this, i.e. in CUDA, HIP, and somewhat OpenCL.~~
**Edit:** After consideration, we don't need to introduce a separate device::hostMalloc API for a functionality that is only present on some backends. We'll instead trigger the hostMalloc behavior by passing a `"{'host': true}"` prop in the device::malloc.
This PR also somewhat changes how the device/pinned host pointers are managed in backends in order to let users obtain the correct underlying pointer via the `memory::ptr()` method automatically, rather than having to pass a particular `occa::properties` setting. Users can also directly pass these hostMalloc'd buffers into kernels since GPU …

[Core] Adding hostMalloc API

---

src/core/kernel.cpp

Since #442 the kernels in our calling code refused to compile, because we set numerical defines.
It seems safe do allow this? It fixes our things at least.

[Fix] kernel header defines can be numbers

---

src/functional/functionDefinition.cpp

Similarly to #414, the Intel compiler is again not happy about shadowing variables. I applied the same renaming as before.

[Fix] Shadowing warnings in functionDefinition.cpp

---

examples/cpp/05_arrays/main.cpp

I hard-coded array lengths to `10` when the host arrays had a size of `5`, causing out-of-bounds errors
Fixes #467

[Examples] Fix out-of-bounds access

---

include/occa/functional/array.hpp

Fixes #471 by inlining `length()`

[Fix][#471] Fixes weird Intel compiler bug

---

examples/fortran/CMakeLists.txt

These tests have been removed, and CMake mustn't try to build them.

[Tests] Fix CMake build of Fortran tests

---

src/occa/internal/modes/openmp/utils.cpp

Previously this used the 'ss' stringstream both inside the closure and outside,
resulting in the first element of the compiler invocation (i.e. the compiler executable)
sometimes ending up in flag, instead of the actual OpenMP flag.

[OpenMP] Fix conflict with re-used stringstream in closure

---

src/occa/internal/utils/sys.cpp

Thanks for the quick responses! I didn't hit this one personally, but I think it theoretically has the same issue as #510, so best to fix that pre-emptively.
In general, can the compiler check for this? Would it be better to not use the `[&]` defaults but use explicit capture lists? Then `-Wshadow` would work, right?

[Internal] Fix another conflict with re-used stringstream in closure

---

src/occa/internal/modes/dpcpp/device.cpp
src/occa/internal/modes/dpcpp/device.hpp

Updates the filename used when compiling DPC++ kernels to work with the new lock-free caching.

[Bugfix][DPCPP] Use correct binary filename when compiling DPC++ kernels

---

src/occa/internal/modes/opencl/device.cpp
src/occa/internal/modes/opencl/polyfill.hpp
src/occa/internal/modes/opencl/streamTag.cpp
src/occa/internal/modes/opencl/streamTag.hpp

Currently using `device::tagStream` and `device::timeBetween` to time kernels with the OpenCL backend results in negative values.

[Bugfix][OpenCL] Update opencl timing to give meaningful results.

---

tests/run_examples

While looking at the CI for another pull request I noticed 
```
./tests/run_examples: line 132: cd: /home/runner/work/occa/occa/examples/c/03_generic_inline_okl: No such file or directory
---[ (OpenMP) c/03_generic_inline_okl ]-----------------------------------------
rm -f /home/runner/work/occa/occa/examples/c/02_background_device/obj/*;
rm -f /home/runner/work/occa/occa/examples/c/02_background_device/main
clang-11  -O3 -march=native -D __extern_always_inline=inline -Wno-variadic-macros -o /home/runner/work/occa/occa/examples/c/02_background_device/main  -fopenmp  /home/runner/work/occa/occa/examples/c/02_background_device/main.c -I/home/runner/work/occa/occa/include -I/home/runner/work/occa/occa/src -L/home/runner/work/occa/occa/lib    -locca -lm -lrt -ldl
Loading cached [addVectors] …
```

[Tests] Fix wrong directory in run_examples script

---

.gitignore

Build dir is commonly a symlink to a scratch space in my setup, it would be nice to ignore that case as well.

[Git] Also ignore build dir if it's a symlink

---

src/occa/internal/lang/builtins/attributes.hpp
src/occa/internal/lang/builtins/attributes/maxInnerDims.cpp
src/occa/internal/lang/builtins/attributes/maxInnerDims.hpp
src/occa/internal/lang/expr/dpcppAtomicNode.cpp
src/occa/internal/lang/modes/cuda.cpp
src/occa/internal/lang/modes/cuda.hpp
src/occa/internal/lang/modes/dpcpp.cpp
src/occa/internal/lang/modes/dpcpp.hpp
src/occa/internal/lang/modes/metal.cpp
src/occa/internal/lang/modes/metal.hpp
src/occa/internal/lang/modes/okl.cpp
src/occa/internal/lang/modes/opencl.cpp
src/occa/internal/lang/modes/opencl.hpp
src/occa/internal/lang/modes/withLauncher.cpp
src/occa/internal/lang/modes/withLauncher.hpp
tests/src/internal/lang/modes/okl.cpp
tests/src/internal/lang/parser/utils.hpp

Closes #307
Introduces a new loop attribute `@max_inner_dims(X, Y, Z)`, where `X`, `Y`, and `Z` are compile-time constants. 
Example usage:
```
@max_inner_dims(16,32)
for(int ib=0; ib < BLOCK_M; ++ib; @outer) {
for(int jb=0; jb < BLOCK_N; ++jb; @outer) {
...
for(int it=0; it < 32; ++it; @inner) {
for(int jt=0; jt < 16; ++jt; @inner) {
...
}
}
}
}
```
When the range of the `@inner` loops within an `@outer` block can be determined at compile-time (e.g., because they are constant), this attribute is added automatically.
If the outermost `@outer`-loop of a for-loop block is decorated with this OKL attribute, the following C++ attributes are added to the resulting backend kernel definitions:
- CUDA/HIP: `__launch_bounds(X*Y*Z)__`
- OpenCL: `__attribute__((reqd_work_group_size(X, Y, Z)))`
- …

[OKL][Feature] `@max_inner_dims` attribute

---

include/occa/core/device.hpp
src/core/device.cpp
src/occa/internal/core/device.hpp
src/occa/internal/modes/cuda/device.cpp
src/occa/internal/modes/cuda/device.hpp
src/occa/internal/modes/cuda/stream.cpp
src/occa/internal/modes/cuda/stream.hpp
src/occa/internal/modes/dpcpp/device.cpp
src/occa/internal/modes/dpcpp/device.hpp
src/occa/internal/modes/hip/device.cpp
src/occa/internal/modes/hip/device.hpp
src/occa/internal/modes/hip/stream.cpp
src/occa/internal/modes/hip/stream.hpp
src/occa/internal/modes/metal/device.cpp
src/occa/internal/modes/metal/device.hpp
src/occa/internal/modes/metal/stream.cpp
src/occa/internal/modes/metal/stream.hpp
src/occa/internal/modes/opencl/device.cpp
src/occa/internal/modes/opencl/device.hpp
src/occa/internal/modes/opencl/polyfill.hpp
src/occa/internal/modes/opencl/stream.cpp
src/occa/internal/modes/opencl/stream.hpp
src/occa/internal/modes/serial/device.cpp
src/occa/internal/modes/serial/device.hpp

Adds `device::wrapStream` method to wrap native backend stream objects. Alternative solution to the functionality proposed in #379.

[Core][Streams] New API to wrap native backend streams

---

src/occa/internal/lang/builtins/attributes.hpp
src/occa/internal/lang/builtins/attributes/noBarrier.cpp
src/occa/internal/lang/builtins/attributes/noBarrier.hpp
src/occa/internal/lang/modes/okl.cpp
src/occa/internal/lang/modes/withLauncher.cpp

Closes #484 
Introduces an attribute `@nobarrier` to disable the automatic addition of barriers after `@inner` loop blocks that write to shared memory.
```
@kernel void f(int N) 
{  
@outer
for(int i=0; i < N; ++i) {
@shared double x[3];
@inner @nobarrier
for(int j=0; j < N; ++j) {
x[j] = 1.0;
}
@inner
for(int j=0; j < N; ++j) {
x[j] = 1.0;
}
}
}
```

Add the `@nobarrier` attribute to stop barriers from being added automatically to `@inner` loop blocks.

---

src/occa/internal/modes/hip/buffer.cpp
src/occa/internal/modes/hip/device.cpp
src/occa/internal/modes/hip/polyfill.hpp
src/occa/internal/modes/hip/utils.cpp

Fixes #546 and addresses a couple other compiler warnings when compiling with HIP support.

[HIP] Fix compiler error and warnings

---

.github/workflows/build.yml
examples/c/01_add_vectors/main.c
examples/c/02_background_device/main.c
src/occa/internal/modes/dpcpp/device.cpp
src/occa/internal/modes/dpcpp/polyfill.hpp

Several hotfixes to ensure that the OpenCL and DPC++ backends don't block PRs.
- Make DPC++ queues in-order
- Exclude some tests involving OpenCL and DPC++ from CI workflows for now

Bugfix  dpcpp examples

---

src/occa/internal/io/cache.cpp

Fix cached file path of "output" to match with the actual file created when checking for its existence.

[#553] Fix broken caching for "output" file

---

src/occa/internal/lang/builtins/attributes/maxInnerDims.cpp
src/occa/internal/lang/modes/oklForStatement.cpp
tests/src/internal/lang/modes/okl.cpp

Closes #567.
- Ensure that only positive values are passes to `@max_inner_dims`
- Check for empty and infinite loops during translation of OKL for loops

Bugfix launch bounds 567

---

src/types/primitive.cpp

Our CI tripped over this when using the PGI compiler. Maybe other compilers with strict warning flags would not like it either.

Fix unreachable statement that makes the PGI compiler unhappy

---

examples/cpp/30_device_function/CMakeLists.txt
examples/cpp/30_device_function/Makefile
examples/cpp/30_device_function/README.md
examples/cpp/30_device_function/addVectors.okl
examples/cpp/30_device_function/main.cpp
examples/cpp/CMakeLists.txt
src/occa/internal/lang/modes/opencl.cpp
src/occa/internal/lang/modes/opencl.hpp
src/occa/internal/modes/opencl/device.cpp

Closes #166 
Closes #241
- Default to OpenCL C v2.0 to use generic address space
- Add environment variable `OCCA_OPENCL_C_VERSION` to override this option:
- E.g., `OCCA_OPENCL_C_VERSION="3.0"` would cause the compiler flag `-cl-std=CL3.0` to be added

Feature ocl device functions

---

src/occa/internal/lang/modes/dpcpp.cpp
tests/src/math/fpMath.cpp
tests/src/math/intMath.cpp

Closes #115
- Add tests for common math functions
- Include `using namespace sycl;` when translating OKL kernels with dpcpp mode

Enable math functions

---

src/occa/internal/modes/dpcpp/device.cpp
src/occa/internal/modes/dpcpp/polyfill.hpp
src/occa/internal/modes/dpcpp/registration.cpp
src/occa/internal/modes/opencl/device.cpp
src/occa/internal/modes/opencl/polyfill.hpp
src/occa/internal/modes/opencl/registration.cpp
src/occa/internal/modes/opencl/utils.cpp
src/occa/internal/modes/opencl/utils.hpp

Closes #422
Updates hashing for the OpenCL and DPCPP backends to be based on the platform and device name, vendor, and version.

OpenCL and DPCPP kernel hashing

---

src/types/json.cpp

Fix an occa::json constructor not setting the type member. 
This bug would cause the following line to fail:
```cpp
occa::json props("name", value);
```
to fail, while the alternative code path: 
```cpp
occa::json props;
props["name"] = value;
```
works as intended.

[JSON] Fix a json constructor not setting the type

---

src/occa/internal/modes/cuda/device.cpp

Since OCCA handles jitting and hashes based on the device architecture, we can compile CUDA code directly to cubin instead of PTX.

Compile CUDA directly to cubin instead of ptx

---

src/occa/internal/lang/qualifier.cpp

The existing qualifiers were shuffled around incorrectly:
For example (original situation, forward loop):
```
inline const long
inline const long long          # qualifiers.push_back(qualifiers[count - 1]);
inline inline long long         # qualifiers[1] = qualifiers[0];
inline inline inline long       # qualifiers[2] = qualifiers[1];
__device__ inline inline long   # qualifiers[0] = qualifier;
```
Should be (new situation, backward loop):
```
inline const long
inline const long long          # qualifiers.push_back(qualifiers[count - 1]);
inline const const long         # qualifiers[2] = qualifiers[1];
inline inline const long        # qualifiers[1] = qualifiers[0];
__device__ inline const long    # qualifiers[0] = qualifier;
```

Fix prepending of qualifiers (addFirst)

---

src/occa/internal/io/cache.cpp
src/occa/internal/lang/modes/withLauncher.cpp

When using OKL + OpenMP code in an MPI-enabled application I started seeing intermittent "Unable to transform OKL kernel" errors, with some indication that some ranks were trying to read incomplete/corrupted intermediate files.
In particular, this piece of code in `src/occa/internal/modes/serial/device.cpp` seemed suspect:
```
[...]
// Cache raw origin
sourceFilename = (
io::cacheFile(filename,
rawSourceFile,
kernelHash,
assembleKernelHeader(kernelProps))
);
if (compilingOkl) {
const std::string outputFile = hashDir + kc::sourceFile;
bool valid = parseFile(sourceFilename,
outputFile,
kernelProps,
metadata);
[...]
```
The first commit adds a `stageFile` wrapper around the file write inside `io::cacheFile`, which fixes the issue for me.
The second commit is an earlier attempt at finding …

Fix cache write races when transformking OKL + Serial/OpenMP kernels

---

examples/CMakeLists.txt

This is recommended by CMake (https://cmake.org/cmake/help/latest/module/FindMPI.html#usage-of-mpiexec)
and allows some extra control for different MPI setups.

[CMake] Add MPIEXEC_PREFLAGS and MPIEXEC_POSTFLAGS to examples

---

CMakeLists.txt
tests/CMakeLists.txt

Small cleanup: I think these are redundant after https://github.com/libocca/occa/pull/533.

[CMake] Remove redundant flags and properties

---

src/occa/internal/lang/modes/oklForStatement.cpp
tests/src/loops/forLoop.cpp

OKL is rather opinionated about what (integer) types are allowed as loop indices. This PR loosens these restrictions somewhat: The code now allows `size_t` and `ptrdiff_t` as types for loop variables.

[OKL] Extend allowed loop index types

---

.github/workflows/build.yml
src/occa/internal/lang/expr/dpcppAtomicNode.cpp
src/occa/internal/lang/modes/dpcpp.cpp

- Updates the namespace of DPC++ features accepted into the SYCL 2020 spec
- Corrects address space of atomic references
- Replaces deprecated barrier calls with `group_barrier`
- Reintroduces some DPC++ tests into the CI pipeline

Fix dpcpp warnings

---

src/occa/internal/lang/modes/oklForStatement.cpp
src/occa/internal/lang/variable.cpp
tests/src/internal/lang/modes/okl.cpp

Closes #610
- Ensures that an OKL for loop counter variable is initialized.
- Provides descriptive error messages related to OKL for loop init statements

[bugfix] OKL for loop init statement

---

src/occa/internal/modes/cuda/device.cpp
src/occa/internal/modes/hip/device.cpp
src/occa/internal/modes/metal/device.cpp

This behaviour was changed for CUDA in the v1.3 release, but getting e.g. information about register spilling is very useful.
Also implement similar behaviour for HIP and Metal.

Show compiler output for kernel if verbose is true

---

.github/workflows/build.yml
cmake/FindOpenCLWrapper.cmake

Updates CMake logic for finding OpenCL headers and library: it should no longer be necessary to define the environment variable `OpenCL_ROOT` on most platforms which have CUDA, HIP, or SYCL installed.

CMake find OpenCL

---

src/occa/internal/modes/cuda/device.cpp
src/occa/internal/modes/dpcpp/device.cpp
src/occa/internal/modes/hip/device.cpp
src/occa/internal/modes/metal/device.cpp
src/occa/internal/utils/sys.cpp

Sometimes the (nvcc) compiler invocations fail without any actual error messages from the compiler itself.
This PR doesn't solve that problem, but it provides some more information about the failure, which might point to a solution in the future.
It also tries to bring the code for various modes closer together in that regard.
The CUDA changes have been tested, but the DPCPP and Metal changes are 'blind' fixes, so some extra eyes from people who can actually run that part of the code would be good to have (in addition to letting the CI run on this PR).

Improve compilation output

---

src/occa/internal/modes/cuda/device.cpp
src/occa/internal/modes/dpcpp/utils.cpp
src/occa/internal/modes/hip/device.cpp
src/occa/internal/modes/opencl/device.cpp
src/occa/internal/modes/serial/device.cpp

Make compiler_flags setting take precedence over the compiler flag env var

---

src/occa/internal/lang/modes/serial.cpp
src/occa/internal/lang/modes/serial.hpp

Adds Dynamic `@exclusive` sizes, closing #121.
When using `@exclusive`s in Serial and OpenMP, OCCA's current behavior is to emulate thread-private variables by turning the `@exclusive` variable into a fixed-size array of length 256. The new behavior is as follows:
1. Default array length is now 1024 (to conform with GPU backends)
2. If `@max_inner_dims` is specified in the `@outer` block containing the `@exclusive`, the array length is set to `@max_inner_dims`. 
3. If the `@inner` block sizes are known at compile time, the array length is set to this size. 
4. If the size determined in 3 is larger than the size determined in 2, an error is thrown.

[Serial] Add dynamic exclusive variable sizes

---

src/occa/internal/modes/openmp/device.cpp

Fixes a bug where both the openmp device::hash() and device::kernelHash were identical to the serial device hashes, with an additional ^ occa::hash("openmp"). This extra hash term would cancel out later (since they're identical) in device::setupKernelInfo, leading to the serial and openmp kernels having the same hash in the cache.

[OpenMP] Fix cancelling kernel hash

---

.github/workflows/build.yml

Older versions of `actions/checkout` used node12, which is now deprecated on GitHub. Version 3 onward use node16.

Updates `actions/checkout` to version 3.

---

src/occa/internal/core/memoryPool.hpp

Testing adding memoryPools into a larger application and hit this issue. 
The comparison function used for the std::set which tracks reservation in memoryPools wasn't strong enough to distinguish between modeMemorys with the same size and location in the memoryPool's allocation.

[MemPool] Fix a bug in reservation tracking in memory pools

---

src/occa/internal/lang/modes/withLauncher.cpp
src/occa/internal/lang/modes/withLauncher.hpp

- Adds the option to control the automatic insertion of `@barrier`s using `occa::json` kernel property `okl/add_barriers`.
- The default value for this property is `true`.
- When `okl/add_barriers` is set to `false`, the net effect is equivalent to adding `@nobarrier` to every `@inner` loop block.
- This property does not affect explicit `@barrier` commands

Adds option to control barrier insertion via kernel properties.

---

src/occa/internal/modes/opencl/polyfill.hpp
src/occa/internal/utils/sys.cpp

Existing condition is meaningless, since the macro is undefined on systems in question:
```
#if OCCA_OS == OCCA_MACOS_OS & (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_12)
```
The code inside the condition is supposed to apply only to OS > 10.12, however it does not, since undefined macro is implicitly evaluated to 0, and you get the following error on 10.6, for example:
```
/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_libocca/libocca/work/occa-1.5.0/src/occa/internal/utils/sys.cpp: In function 'int occa::sys::getTID()':
/opt/local/var/macports/build/_opt_PPCRosettaPorts_devel_libocca/libocca/work/occa-1.5.0/src/occa/internal/utils/sys.cpp:406:7: error: 'pthread_threadid_np' was not declared in this scope; did you mean 'pthread_is_threaded_np'?
406 | …
```

Fixes for macOS

---

examples/cpp/30_device_function/addVectors.okl
src/occa/internal/lang/modes/dpcpp.cpp

- SYCL device functions can only be declared with `SYCL_EXTERNAL` if they have external linkage under the normal C++ rules.
- Avoids adding the `SYCL_EXTERNAL` macro to functions declared with the `static` qualifier. 
Closes #660

Correctly handle linkage qualifiers for dpcpp device functions.

---

src/occa/internal/utils/gc.tpp

Fixing a simple bug that access element when it was not found.

[bugfix] Remove ring entry reference if exists

---

include/occa/c/base.h
include/occa/core/device.hpp
src/c/base.cpp
src/core/device.cpp
src/occa/internal/core/device.cpp
src/occa/internal/core/device.hpp
src/occa/internal/modes/cuda/device.cpp
src/occa/internal/modes/cuda/device.hpp
src/occa/internal/modes/hip/device.cpp
src/occa/internal/modes/hip/device.hpp

This is an updated version of draft PR #606 to add a C API to get the arch version numbers for a given device. This change would still support cuda and hip for now.

Add C API to get the arch version from a device

---

include/occa/c/base.h
src/c/base.cpp

C api for unwrap to get native stream pointer. This is one of the data types supports unwarp, and exposure of them to C API could be done need based IMO as CPP API has its complete support. This is related to an issue #664.

C api for 'unwrap' occaStream type

---

include/occa/core/kernelArg.hpp
src/core/kernelArg.cpp
tests/files/argKernel.okl
tests/src/c/kernel.cpp
tests/src/core/kernel.cpp

Title says it all. tests/src/core/kernel.cpp shows the intended usage, and tests/src/c/kernel.cpp shows the equivalent C API usage (C needs the argument wrapped in an occaStruct object).

[Core] Allow passing general objects by value to kernels

---

src/occa/internal/modes/dpcpp/polyfill.hpp

Ref: https://gcc.gnu.org/gcc-13/porting_to.html#header-dep-changes
Resolves: #683

Add missing header <cstdint> to fix building with GCC 13

---

CMakeLists.txt
Makefile
src/core/base.cpp
src/occa/internal/utils/env.cpp
src/occa/internal/utils/gc.hpp
src/occa/internal/utils/gc.tpp
tests/src/internal/utils/gc.cpp

This is a change related to an issue #657. This can be a minimal change possibly being made to enable sharable OCCA device by multiple threads. With this change two threads invoking kernel builds/runs simultaneously could be demonstrated in our application. Unlocking broader support for multi-threading might require more changes, but it would probably be better to have that happens when an actual case presented to ensure necessary changes and testing IMO. As suggested in the issue, this feature is currently hidden behind a cmake build option (turned off by default), so it is required to be turned on by a user to enable it.

[#657] Relax thread-local constraint for the device shrable by multiple threads

---

examples/cpp/18_nonblocking_streams/main.cpp
src/loops/typelessForLoop.cpp
src/occa/internal/lang/modes/serial.cpp
src/occa/internal/modes/cuda/device.cpp
src/occa/internal/modes/dpcpp/device.cpp
src/occa/internal/modes/hip/device.cpp
src/occa/internal/modes/opencl/device.cpp
src/occa/internal/modes/serial/device.cpp
tests/src/c/kernel.cpp
tests/src/core/kernel.cpp
tests/src/math/fpMath.cpp
tests/src/math/intMath.cpp

Add kernel/include_occa and kernel/link_occa properties to control including and linking occa into kernels. This PR is a replica of the original PR #603 by @SFrijters with very minor cleanup (removed changes already merged in, and squash the original commits), just in case if there would be any further changes required.
Original description by @SFrijters in the PR was:
**Recently I have been debugging a segmentation fault in our code that seems to have been caused by transitive dependencies of occa. During this process I noticed that all kernels get linked to libocca and occa headers are #included at the top of the kernel code. However, none of our kernels require anything from inside occa, so I think it would be nice to be able to control this. Not linking in occa speeds things up a …

Add kernel/include_occa and kernel/link_occa properties

---

src/occa/internal/modes/hip/polyfill.hpp
src/occa/internal/modes/hip/utils.cpp

gcnArch has been deprecated for quite some time now.
gcnArch being an int type can not handle the names like gfx90a.
ROCm 6.0 will remove that particular entry all together.

Use gcnArchName instead of gcnArch. 

---

scripts/codegen/setup_kernel_operators.py

Update the value of the maximum arguments in code generation python script which was missing from the PR #671. This should fix the incorrect behavior for a kernel having the number of arguments greater than 50.

Update MAX_ARGS value in the code generation script

---

src/core/memory.cpp

Let some memory methods return quickly instead of error when they are zero size allocations.
Addresses #648, but in a different manner than PR #649. 
@MalachiTimothyPhillips can you weight in if this would solve your issue?

[Core] Zero size memory quick returns

---

src/occa/internal/core/launchedDevice.cpp
src/occa/internal/io/utils.cpp
src/occa/internal/io/utils.hpp
src/occa/internal/modes/serial/device.cpp

This aids debugging, e.g. in stack traces or when setting breakpoints.

Include original file name in the cached sources

---

src/occa/internal/modes/dpcpp/device.cpp
src/occa/internal/modes/dpcpp/device.hpp
src/occa/internal/modes/dpcpp/registration.cpp
src/occa/internal/modes/dpcpp/utils.cpp
src/occa/internal/modes/dpcpp/utils.hpp

- In the SYCL 2020 spec, the default device and context constructors use the default device selector
- The default device selector may return a device from a different platform, which can result in runtime errors
- To avoid this, directly initialize the device and context instead of using assignment

Avoid unintended calls to sycl default device/context ctor.

---

src/occa/internal/lang/modes/dpcpp.cpp

- Currently `@shared` declarations with qualifiers lead to compilation errors since we use `auto&` 
- Example: `@shared long int x[3]` is translated to `long auto& x = ...` instead of `auto& x  = ...`
- Qualifiers are still included in the template parameter of the RHS call for allocating local memory.

Remove qualifiers from lhs of sycl local variable declarations.

---

src/occa/internal/modes/dpcpp/kernel.cpp

- Dynamically loaded device code is effectively a shared resource managed by the sycl runtime. 
- Unloading the dynamic library for our kernels can corrupt objects owned by the sycl implementation (e.g., kernel bundles), leading to runtime errors. 
- Avoid calling `dlclose` as a temporary workaround until issues related to dynamically loaded device code are resolved by the sycl spec and/or implementers. (See discussion [here](https://intel.github.io/llvm-docs/design/SharedLibraries.html))

[WORKAROUND] Avoid unloading dynamic libraries for dpcpp kernels.

---

src/occa/internal/modes/hip/kernel.cpp
src/occa/internal/modes/hip/kernel.hpp

Fixes an issue where large (`>sizeof(void*)`) arguments passed by value in HIP mode would overflow the allocated space for kernel arguments passed to `hipModuleLaunchKernel`
Thanks to @ooreilly for reporting the issue!

[HIP] Resize the argument buffer to be able to fit large arguments passed by value

---

.github/workflows/build.yml

- The inline kernel cpp example passes for dpcpp mode on the second pass
- There is likely a bug related to kernel jitting
- For now remove from the GitHub CI pipeline since it will cause unrelated to PRs to fail checks

Remove dpcpp from modes tested with inline kernel example on GitHub

---

CMakeLists.txt

- Intended for CMake builds which add occa as a subdirectory.
- Closes #692

Sets `OCCA_<MODE>_ENABLED` in CMake parent scope.

---

src/occa/internal/core/device.cpp
src/occa/internal/core/device.hpp

Bugfix: device::finishAll()`

---

cmake/OCCAConfig.cmake.in

In a chain of cmake package config projects using find_dependency(), where each would use the same code to temporarily adapt the module path, the path would end up empty in the end, even if it wasn't empty before, because of the unset() call of a not-package-specific variable. Therefore, make the variable name package specific.

cmake: Small fix to prevent empty module path

---

src/occa/internal/core/memory.cpp
tests/src/core/memory.cpp

Fixes corruption of memory datatypes caused by short circuit logic in `modeMemory_t::slice`

---

.github/workflows/build.yml
src/occa/internal/modes/opencl/device.cpp
src/occa/internal/modes/opencl/device.hpp
src/occa/internal/modes/opencl/polyfill.hpp
src/occa/internal/modes/opencl/registration.cpp
src/occa/internal/modes/opencl/utils.cpp
src/occa/internal/modes/opencl/utils.hpp
tests/src/math/fpMath.cpp
tests/src/math/intMath.cpp

Refactor OpenCL mode and updates CI testing

---

src/occa/internal/lang/attribute.cpp
src/occa/internal/lang/attribute.hpp
src/occa/internal/lang/builtins/attributes.hpp
src/occa/internal/lang/builtins/attributes/simdLength.cpp
src/occa/internal/lang/builtins/attributes/simdLength.hpp
src/occa/internal/lang/modes/dpcpp.cpp
src/occa/internal/lang/modes/dpcpp.hpp
src/occa/internal/lang/modes/okl.cpp
src/occa/internal/lang/modes/withLauncher.cpp
tests/src/internal/lang/modes/dpcpp.cpp

- Introduces the `@simd_length` attribute and kernel property
- For dpcpp mode these can be used to prescribe which subgroup size will be used
- OpenCL and OpenMP modes could make use of this property in the future
Closes #693

Set SYCL subgroup size via kernel property or `@simd_length` attribute.

---

.github/workflows/build.yml
examples/fortran/01_add_vectors/main.f90
examples/fortran/03_static_compilation/main.f90
examples/fortran/09_streams/main.f90
include/occa/core/memory.hpp
include/occa/functional/array.hpp
include/occa/functional/typelessArray.hpp
src/core/memory.cpp
tests/src/core/memory.cpp

**BREAKING** Make memory copies data type aware for consistency.

---

include/occa/core/memory.hpp
include/occa/functional/array.hpp
src/core/memory.cpp
tests/src/core/device.cpp
tests/src/core/memory.cpp

**BREAKING** Return the number of `dtype` entries from `memory::size()`.

---

src/occa/internal/lang/builtins/types.cpp
src/occa/internal/lang/builtins/types.hpp
src/occa/internal/lang/keyword.cpp
src/occa/internal/lang/loaders/typeLoader.cpp
src/occa/internal/lang/loaders/typeLoader.hpp
src/occa/internal/lang/modes/okl.cpp
src/occa/internal/lang/qualifier.cpp
src/occa/internal/lang/qualifier.hpp
src/occa/internal/lang/type/vartype.cpp
src/occa/internal/lang/type/vartype.hpp
src/occa/internal/lang/variable.cpp
src/occa/internal/lang/variable.hpp

This added a generic ability of the OCCA parser to allow `qualifier_t` tokens to take arguments, and adds the `__attribute__` keyword as a qualifier. Consequently, some initial `__attribute__` and `dllexport__` statements should be possible. 
This is useful when using some backend-specific compiler attributes on variables/functions, e.g.
```c++
@kernel
__attribute__((amdgpu_waves_per_eu(1,1)))
void myKernel(...)
```
or when needing specific variable traits, e.g. with AMD GPUs and MFMA instructions:
```c++
for(int l=0;l<64;++l;@inner(0)){
__attribute__((__vector_size__(4 * 8))) double C = {0.};
...
// C = A*B
C = __builtin_amdgcn_mfma_f64_16x16x4f64(A, B, C, 0, 0, 0);
}
```

Initial support for compiler attribute statements

---

CMakeLists.txt

Without this, `CUDA::cuda_driver` target is not linked to libocca during consumption and as a result there is a build problem: libcuda.so cannot be found. This occurs on machines which do not have CUDA lib in default, compiler included directories (e.g. in /lib64)

cmake: expose CUDA::cuda_driver dependency in use

---

src/occa/internal/utils/sys.cpp

Not sure why it was conditioned on Clang at all, since `clock_gettime` is provided by SDK and not compiler. Fix that.
Include `AvailabilityMacros.h` – apparently nothing in the codebase does that (or did I miss it?).
Amend fallback code for threadid for older macOS.

sys.cpp: fix code fallbacks for older Darwin

---

cmake/FindMETAL.cmake

Using `target_link_libraries` instead of `set_target_properties` fixes the link line, so that
it includes `Metal` and `CoreServices`.
Closes #674

Fixing FindMETAL.cmake

---

src/occa/internal/utils/sys.cpp

@kris-rowe Will this be an agreeable fix? My earlier PR apparently broken Linux build https://github.com/libocca/occa/pull/739 and reverting that broken macOS https://github.com/libocca/occa/commit/3cba0841b2b87678da53e0b311cb7e162d781181
We can fix macOS without touching Linux code.

sys.cpp: fix macOS without breaking Linux
